source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/com.gaurav.dsi.einvoicing.factories.GenerateQRCodeForEInvoicingProcessFactory.xml,\
               OSGI-INF/com.gaurav.dsi.einvoicing.event.GetQRCodeOnEInvoicingEventHandler.xml
