source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/com.gaurav.dsi.docactionmultipledocs.process.factory.DocActionMultipleDocumentsProcessFactory.xml
