output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/InvestmentProcessFactory.xml,\
               OSGI-INF/InvestmentCallOutFactory.xml,\
               OSGI-INF/com.gaurav.dsi.event.CouponScheduleEventHandler.xml
source.. = src/
